import * as React from "react";
import { images } from "@/constants";
import Image from "next/image";
import { BarChart } from "@mui/x-charts/BarChart";
import { BorderBeam } from "@/components/ui/border-beam";

const About = () => {
  return (
    <div className="container mx-auto px-4 py-8 space-y-16 mt-6">
      {/* About Us Section */}
      <section>
        <div className="flex flex-col-reverse md:flex-row items-center justify-between gap-8">
          <div className="w-full md:w-1/2 flex justify-center">
            <Image
              src={images.chart1}
              alt="Financial Chart"
              width={600} // Reduced image size
              height={500}
              className="object-cover rounded-lg"
              loading="lazy" // Lazy loading the image
            />
          </div>

          <div className="w-full md:w-1/2 bg-gray-100 rounded-lg p-6">
            <div className="relative flex h-auto p-6 py-10 w-full flex-col items-center justify-center overflow-hidden rounded-lg border bg-background md:shadow-xl">
              <span className="pointer-events-none whitespace-pre-wrap  from-black to-gray-300/80 bg-clip-text text-left text-xl leading-none text-gray-800 ">
                <h1 className="px-4 text-left text-3xl md:text-4xl font-semibold mb-4">
                  About Us
                </h1>
                Our conviction in equity investment is founded on the belief
                that long-term participation in the equity markets yields
                substantial rewards. This in-depth analysis of multi-bagger
                stocks in India over the period from 2004 to 2024 underscores
                the remarkable returns generated by various companies over a
                two-decade horizon. It highlights the transformative potential
                of equities as a wealth creation vehicle, emphasizing the
                sustained value they can deliver to committed investors over
                extended timeframes.
              </span>
              <BorderBeam size={250} duration={12} delay={9} />
            </div>
          </div>
        </div>
      </section>

      {/* Team Section */}
      <section>
        <div className="flex flex-col-reverse md:flex-row-reverse items-center justify-between gap-8">
          {/* Right Div - Image with lazy loading */}
          <div className="w-full md:w-1/2 flex justify-center">
            <Image
              src={images.sihoplatform}
              alt="SIHO Team"
              width={600} // Reduced image size
              height={500}
              className="object-cover rounded-lg "
              loading="lazy" // Lazy loading the image
            />
          </div>
          {/* Left Div - Paragraph with Heading */}
          <div className="w-full md:w-1/2 p-6  bg-gray-100  rounded-lg">
            <div className="relative flex h-auto p-6 py-10 w-full flex-col items-center justify-center overflow-hidden rounded-lg border bg-background md:shadow-xl">
              <span className="pointer-events-none whitespace-pre-wrap  from-black to-gray-300/80 bg-clip-text text-left text-xl  leading-none text-gray-800 ">
                <h1 className="px-4 text-left text-3xl md:text-4xl font-semibold mb-4">
                  Team
                </h1>
                At SIHO Research, our team is comprised of highly skilled
                professionals, including Software Architects, MBAs, CFAs, AI
                Engineers, and Data Engineers, all driven by a deep commitment
                to investing. For more than 15 years, we have harnessed the
                power of our proprietary SIHO platform to inform and optimize
                our investment strategies, ensuring data-driven and strategic
                decision-making.
              </span>
              <BorderBeam size={250} duration={12} delay={9} />
            </div>
          </div>
        </div>
      </section>

      {/* Vision Section */}
      <section>
        <div className="flex flex-col-reverse md:flex-row items-center justify-between gap-8">
          <div className="w-full md:w-1/2 flex justify-center">
            <Image
              src={images.simplifyInvesting}
              alt="Simplify Investing"
              width={600} // Reduced image size
              height={500}
              className="object-cover rounded-lg "
              loading="lazy" // Lazy loading the image
            />
          </div>

          <div className="w-full md:w-1/2 p-6  bg-gray-100  rounded-lg">
            <div className="relative flex h-auto p-6 py-10 w-full flex-col items-center justify-center overflow-hidden rounded-lg border bg-background md:shadow-xl">
              <span className="pointer-events-none whitespace-pre-wrap  from-black to-gray-300/80 bg-clip-text text-left text-xl leading-none text-gray-800 ">
                <h1 className="px-4 text-left text-3xl md:text-4xl font-semibold mb-4">
                  Vision
                </h1>
                At SIHO Research, our vision is to simplify the investment
                process by staying true to the core principles of successful
                investing. By leveraging cutting-edge technology alongside
                comprehensive equity research, we have created a platform that
                not only understands the intricacies of the financial markets
                but also streamlines the investment process. Our platform is
                designed to execute with precision and efficiency, helping
                investors make informed, confident decisions that align with
                their financial goals.
              </span>
              <BorderBeam size={250} duration={12} delay={9} />
            </div>
          </div>
        </div>
      </section>

      {/* Simplify Investing Section */}
      <section>
        <div className="flex flex-col-reverse md:flex-row-reverse items-center justify-between gap-8">
          {/* Right Div - Image with lazy loading */}
          <div className="w-full md:w-1/2 flex justify-center">
            <Image
              src={images.helpOthers}
              alt="Help Others"
              width={500} // Reduced image size
              height={400}
              className="object-cover rounded-lg "
              loading="lazy" // Lazy loading the image
            />
          </div>

          <div className="w-full md:w-1/2 p-6 bg-gray-100  rounded-lg">
            <div className="relative flex h-auto p-6 py-10 w-full flex-col items-center justify-center overflow-hidden rounded-lg border bg-background md:shadow-xl">
              <span className="pointer-events-none whitespace-pre-wrap  from-black to-gray-300/80 bg-clip-text text-left text-xl leading-none text-gray-800 ">
                <h1 className="px-4 text-left text-3xl md:text-4xl font-semibold mb-4">
                  Simplify Investing
                </h1>
                At SIHO Research, we are dedicated to sharing our insights and
                best practices with individuals who aspire to grow their wealth
                with confidence. Our mission is to empower people to build and
                compound their wealth over time, enabling them to achieve
                financial freedom and be better prepared for unexpected
                financial challenges.
              </span>
              <BorderBeam size={250} duration={12} delay={9} />
            </div>
          </div>
        </div>
      </section>

      {/* Impact Section */}
      <section>
        <div className="flex flex-col-reverse md:flex-row items-center justify-between gap-8">
          {/* Left Div - Graph */}
          <div className="w-full md:w-1/2 flex justify-center">
            <BarChart
              xAxis={[
                {
                  scaleType: "band",
                  data: [
                    "2011",
                    "2012",
                    "2013",
                    "2014",
                    "2015",
                    "2016",
                    "2017",
                    "2018",
                    "2019",
                    "2020",
                    "2021",
                    "2022",
                    "2023",
                    "2024",
                  ],
                },
              ]}
              series={[
                {
                  data: [
                    1, 1.42, 2.3, 2.6, 4.4, 4.51, 6.15, 6.5, 7.11, 8.63, 13.43,
                    15.29, 20.43, 26.93,
                  ],
                },
              ]}
              width={600} // Reduced image size
              height={500}
            />
          </div>

          <div className="w-full md:w-1/2 bg-gray-100  p-6  rounded-lg">
            <div className="relative flex h-auto p-6 py-10 w-full flex-col items-center justify-center overflow-hidden rounded-lg border bg-background md:shadow-xl">
              <span className="pointer-events-none whitespace-pre-wrap  from-black to-gray-300/80 bg-clip-text text-left text-xl  leading-none text-gray-800 ">
                <h1 className="px-4 text-left text-3xl md:text-4xl font-semibold mb-4">
                  Impact
                </h1>
                Our journey has been both inspiring and rewarding, and we are
                thrilled to share the advancements we’ve made along the way.
                Below is an illustration of our journey, highlighting the growth
                we have achieved over the years.
              </span>
              <BorderBeam size={280} duration={15} delay={5} />
            </div>
          </div>
        </div>
      </section>
    </div>
  );
};

export default About;
